apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "react-app-demo"
  description: "acme test"
  annotations:
    github.com/project-slug: OpsVerseIO/react-app-demo
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://pearjet.observe.devopsnow.cloud/d/PTSqcpJWk/nodejs-apps?orgId=1
      title: Metrics Dashboard
      icon: dashboard
spec:
  type: website
  lifecycle: experimental
  owner: "user:sat@devopsnow.io"
