apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "react-app-demo"
  description: "acme test"
  annotations:
    github.com/project-slug: OpsVerseIO/react-app-demo
    argocd/app-name: acme-sigma-devportal
    prometheus.io/rule: container_memory_usage_bytes{}
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: OpsVerseIO_installers
    # pagerduty.com/integration-key: acb295f3e5ee4a07c0c54df22204e2e0
    zenduty.com/integration-key: 9210b83e-74c1-418a-ad4b-0e5ee23af499
    grafana/tag-selector: "admin-console"
    pagerduty.com/integration-key: 1e2a74b8b29d4304c0ce87303bf0a72e
    #jira/project-key: NOW
    #jira/token-type: Bearer
    gitlab.com/project-id: '37036847'
    circleci.com/project-slug: github/aditya-opsverse/circleCI
  links:
    - url: https://pearjet.observe.devopsnow.cloud/d/PTSqcpJWk/nodejs-apps?orgId=1
      title: Metrics Dashboard
      icon: dashboard
    - url: https://devops-machine.atlassian.net/jira/software/c/projects/NOW/boards/4
      title: Jira board
      icon: dashboard
  tags:
    - node-js
    - react
    - demo
spec:
  #type: website
  type: service
  lifecycle: experimental
  owner: "user:sat@devopsnow.io"
  system: public-websites
