apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "react-app-demo"
  description: "acme test"
  annotations:
    github.com/project-slug: OpsVerseIO/react-app-demo
    argocd/app-name: acme-sigma-devportal
    prometheus.io/rule: container_memory_usage_bytes{}
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: OpsVerseIO_installers
    pagerduty.com/integration-key: acb295f3e5ee4a07c0c54df22204e2e0
    zenduty.com/integration-key: f7706a29-20ff-4b13-b9eb-f3994de322f3
  links:
    - url: https://pearjet.observe.devopsnow.cloud/d/PTSqcpJWk/nodejs-apps?orgId=1
      title: Metrics Dashboard
      icon: dashboard
    - url: https://devops-machine.atlassian.net/jira/software/c/projects/NOW/boards/4
      title: Jira board
      icon: dashboard
  tags:
    - node-js
    - react
    - demo
spec:
  # type: website
  type: service
  lifecycle: experimental
  owner: "user:sat@devopsnow.io"
  system: public-websites
