apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "react-app-demo"
  description: "acme test"
  annotations:
    github.com/project-slug: OpsVerseIO/react-app-demo
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: "sat@devopsnow.io"
